load("@com_github_bazelbuild_buildtools//buildifier:def.bzl", "buildifier")

buildifier(
    name = "buildifier-diff",
    mode = "diff",
)

buildifier(
    name = "buildifier",
    lint_mode = "warn",
)
