name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        run: |
          echo "build --host_platform=@rules_haskell//haskell/platforms:linux_x86_64_nixpkgs" > .bazelrc.local
          nix-shell --pure --run 'bazel build //...'
          nix-shell --pure --run 'bazel run clotestbin'
          nix-shell --pure --run 'bazel run clotestbin-cc'
          nix-shell --pure --run 'bazel run hello-java'
          nix-shell --pure --run 'bazel run //:buildifier-diff'
